### ISSUE TITLE
Test deployment

### ISSUE THREAD

**Issue by jeanmidevacc** [michael-erasmus/dash-docker#2]
Hello Michael, 

I am currently trying your method and the building working fine but when i try to reach the application it doesn't work.
![image](https://user-images.githubusercontent.com/23313992/32453001-0a544600-c313-11e7-9471-a84aee35bf82.png)

I am a newcomer in the Docker world so maybe I missed something during the setup, I am actually trying to deploy (contain) on my Mac this dash application. I read the documentation of dash for the Heroku deployment they use the dependency gunicorn but I am not sure that it will help me for my issue.

So if you have any resources that could help me to better understanding the process to contain a dash app it will be super nice.

**Comment by michael-erasmus** [comment]
Hey @jeanmidevacc, what url are you using there? 

After running the container, I can connect to it on `http://127.0.0.1:8050`

I'm actually running on Linux, so I'm not sure if it works slightly different on a Mac.

**Comment by michael-erasmus** [comment]
@jeanmidevacc maybe you could also try running it without the `--net=host` flag

```
docker run --rm -it  -v "$PWD":/usr/src/myapp michaelerasmus/dash
```

**Comment by jeanmidevacc** [comment]
the url is the http://127.0.0.1:8050.

Ah good to know that you are running on Linux, I have a spare Linux machine so I will run some test on this one to see if there is the issue.

I try the command without the --net flag it doesn't work.

Thanks for your feedback, I will keep you informed of my test on Linux.

**Comment by jeanmidevacc** [comment]
Hello Michael,

I have made some tests on my Linux machine and your process working great.

I have just a question, I cannot access the app from the IP address of my machine there is something to do in the Dockerfile or when I used the docker run command?

**Comment by jeanmidevacc** [comment]
Sorry I found the element to modify the command  (--net=none)

I am closing the issue
